### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (512,512,4) (512,512,3)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Pfaeff/sd-web-ui-scripts#1]
With the last AUTOMATIC1111/stable-diffusion-webui
```
Traceback (most recent call last):
  File "A:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "A:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "A:\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "A:\stable-diffusion-webui\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "A:\stable-diffusion-webui\scripts\moisaic.py", line 327, in run
    output_image_np = np.multiply(output_image_np, mask) + np.multiply(crop, 1.0 - mask)
ValueError: operands could not be broadcast together with shapes (512,512,4) (512,512,3)
```

**Comment by steto123** [comment]
i have the same error
